= REST Docs 문서 만들기 (글의 제목)
부제목(부제)
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:

[[Member-API]]
== Member API

[[Member-로그인]]
=== 로그인
operation::login[snippets='custom,http-response,response-headers']
=== 회원 닉네임으로 조회
operation::get-member-info-by-nickname[snippets='http-request,http-response,response-fields']
=== 회원 닉네임 중복조회
operation::check-nickname-duplicate[snippets='http-request,http-response,response-fields']
=== 회원 닉네임 설정
operation::set-nickname[snippets='http-request,request-fields,http-response,response-fields']
=== 회원 닉네임 변경
operation::change-nickname[snippets='http-request,request-fields,http-response,response-fields']
=== 회원 아이콘리스트 조회
operation::get-icons[snippets='http-request,path-parameters,http-response,response-fields']
=== 회원 대표아이콘 설정
operation::set-repIcon[snippets='http-request,request-fields,http-response,response-fields']
=== 회원 아이콘 추가
operation::add-Icon[snippets='http-request,request-fields,http-response,response-fields']

[[Team-API]]
== Team API

=== 팀 초대 링크 조회
operation::team-get-invite-link[snippets='http-request,path-parameters,http-response,response-fields']
=== 팀 모든 아이콘 조회
operation::team-get-icons[snippets='http-request,path-parameters,http-response,response-fields']
=== 팀 대표 아이콘 설정
operation::team-set-repIcon[snippets='http-request,request-fields,http-response,response-fields']
=== 팀 아이콘 추가
operation::team-add-Icon[snippets='http-request,request-fields,http-response,response-fields']
=== 팀 정보 변경
operation::team-change-teamInfo[snippets='http-request,request-fields,http-response,response-fields']

[[Registraion-API]]
== Registration API

=== 팀 생성
operation::create-team[snippets='http-request,request-fields,http-response,response-fields']
=== 팀 삭제
operation::delete-team[snippets='http-request,request-fields,http-response,response-fields']
=== 팀 상세 정보 조회
operation::get-team-detail-info[snippets='http-request,path-parameters,http-response,response-fields']
=== 회원이 가입한 팀 정보 조회
operation::get-member-joined-team[snippets='http-request,path-parameters,http-response,response-fields']
=== 회원의 팀 탈퇴
operation::resign-team[snippets='http-request,request-fields,http-response,response-fields']
=== 리더의 회원 강퇴
operation::expel-member[snippets='http-request,request-fields,http-response,response-fields']
=== 리더의 그룹장 위임
operation::assign-leader-to-follower[snippets='http-request,request-fields,http-response,response-fields']

[[Exercise-API]]
== Exercise-API

=== 운동결과 저장 및 달성률 조회
operation::exercise-result[snippets='http-request,request-fields,http-response,response-fields']
=== 팀 월 단위 운동기록 조회
operation::exercise-team-monthly[snippets='http-request,request-parameters,http-response,response-fields']
=== 팀 누적 운동기록 조회
operation::exercise-team-history[snippets='http-request,request-parameters,http-response,response-fields']
=== 개인 월 단위 운동기록 조회
operation::exercise-member-monthly[snippets='http-request,request-parameters,http-response,response-fields']
=== 개인 누적 운동기록 조회
operation::exercise-member-history[snippets='http-request,request-parameters,http-response,response-fields']